/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class poop_BasicOperation */

#ifndef _Included_poop_BasicOperation
#define _Included_poop_BasicOperation
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     poop_BasicOperation
	 * Method:    exeCpp
	 * Signature: (IIIIZIZZZI)[I
	 */
	JNIEXPORT jintArray JNICALL Java_poop_BasicOperation_exeCpp
	(JNIEnv *, jobject, jint, jint, jint, jint, jboolean, jint, jboolean, jboolean, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
